language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install git+https://github.com/ptrstn/deepl-translate
  - pip install --upgrade pytest pytest-cov codecov
  - pip install -e .

script:
  - pytest --cov .
  - plagiarize

after_success:
  - codecov
